ALTER TABLE certificates
  ADD COLUMN IF NOT EXISTS language_code TEXT REFERENCES languages(code),
  ADD COLUMN IF NOT EXISTS certificate_code TEXT,
  ADD COLUMN IF NOT EXISTS final_grade NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS issue_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS pdf_url TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_certificates_code ON certificates(certificate_code) WHERE certificate_code IS NOT NULL;

ALTER TABLE batches
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();