-- Seed 5 more news articles
INSERT INTO public.news (title, slug, content, excerpt, category, status, author_id, published_at)
VALUES
  ('EduLingo Luncurkan Program Bahasa Jepang dengan Pengajar Native', 'peluncuran-program-bahasa-jepang', 'EduLingo resmi meluncurkan program Bahasa Jepang terbaru yang dirancang khusus untuk pelajar Indonesia. Program ini menghadirkan pengajar native speaker bersertifikat dari Jepang yang berpengalaman dalam mengajar bahasa Jepang sebagai bahasa asing.\n\nKurikulum disusun berdasarkan standar JLPT (Japanese Language Proficiency Test) dari level N5 hingga N1, sehingga siswa dapat mempersiapkan diri untuk ujian sertifikasi internasional secara terstruktur.\n\nFitur unggulan program ini meliputi sesi praktik langsung dengan native speaker, materi interaktif berbasis multimedia, dan akses ke komunitas belajar yang aktif. Setiap siswa juga mendapatkan umpan balik personal dari pengajar untuk mempercepat proses pembelajaran.\n\nPendaftaran program Bahasa Jepang sudah dibuka dan tersedia dalam paket Free, Pro, dan Premium. Siswa baru dapat mengikuti placement test gratis untuk menentukan level yang tepat.', 'Program terbaru ini menghadirkan pengajar native Jepang bersertifikat, kurikulum berbasis JLPT, dan sesi praktik langsung dengan native speaker.', 'Program Baru', 'published', 'a0000000-0000-0000-0000-000000000001', '2026-07-15T00:00:00Z'),
  ('Program Beasiswa EduLingo 2026 untuk 100 Siswa Berprestasi', 'beasiswa-edulingo-2026', 'EduLingo membuka program beasiswa penuh untuk 100 siswa berprestasi dari seluruh Indonesia. Program ini merupakan komitmen EduLingo dalam mendukung akses pendidikan bahasa asing yang berkualitas bagi semua kalangan.\n\nBeasiswa mencakup akses penuh ke semua program kursus selama satu tahun, termasuk kelas live, materi belajar, dan sesi konsultasi dengan pengajar. Pendaftaran beasiswa dibuka hingga 31 Agustus 2026.\n\nPersyaratan utama meliputi: Warga Negara Indonesia, usia 16-25 tahun, IPK minimal 3.0 (untuk pelajar/mahasiswa) atau surat rekomendasi, dan esai motivasi tentang pentingnya bahasa asing. Seleksi akan dilakukan melalui tes bahasa dan wawancara.', 'EduLingo membuka 100 beasiswa penuh untuk siswa berprestasi dari seluruh Indonesia. Pendaftaran dibuka hingga 31 Agustus 2026.', 'Beasiswa', 'published', 'a0000000-0000-0000-0000-000000000001', '2026-07-05T00:00:00Z'),
  ('Webinar: Kuasai Bahasa Asing untuk Tingkatkan Peluang Karier Global', 'webinar-bahasa-asing-karier', 'EduLingo mengundang kamu untuk mengikuti webinar gratis bertema "Kuasai Bahasa Asing untuk Tingkatkan Peluang Karier Global". Acara ini akan menghadirkan praktisi HRD dari perusahaan multinasional dan seorang polyglot yang menguasai 7 bahasa asing.\n\nWebinar akan membahas strategi efektif belajar bahasa asing di tengah kesibukan, bahasa asing apa yang paling dibutuhkan di dunia kerja saat ini, dan bagaimana memaksimalkan sertifikat bahasa untuk melamar kerja.\n\nAcara akan dilaksanakan pada hari Sabtu, 10 Agustus 2026 pukul 10.00 - 12.00 WIB melalui Zoom. Peserta mendapatkan e-sertifikat dan akses rekaman webinar. Pendaftaran gratis melalui halaman event EduLingo.', 'Webinar gratis bersama praktisi HRD dan polyglot. Dapatkan tips belajar bahasa asing yang efektif untuk dunia profesional.', 'Event', 'published', 'a0000000-0000-0000-0000-000000000001', '2026-06-28T00:00:00Z'),
  ('Sertifikat Digital dengan QR Verification Kini Tersedia', 'sertifikat-qr-verification', 'Mulai sekarang, setiap siswa yang lulus kursus di EduLingo akan mendapatkan sertifikat digital yang dilengkapi dengan QR Verification. Teknologi ini memungkinkan perusahaan atau institusi untuk memverifikasi keaslian sertifikat secara instan.\n\nSertifikat digital EduLingo mencakup informasi detail seperti nama siswa, program yang diselesaikan, level yang dicapai, tanggal kelulusan, dan nilai akhir. QR code yang tertera dapat dipindai menggunakan smartphone untuk verifikasi langsung ke sistem EduLingo.\n\nFitur QR Verification tersedia untuk semua siswa yang menyelesaikan program berbayar (Pro dan Premium). Sertifikat dapat dibagikan langsung ke LinkedIn atau diunduh dalam format PDF.', 'Siswa yang lulus kursus kini mendapatkan sertifikat digital yang bisa diverifikasi via QR code, memudahkan verifikasi oleh perusahaan atau institusi.', 'Fitur', 'published', 'a0000000-0000-0000-0000-000000000001', '2026-06-20T00:00:00Z'),
  ('EduLingo Jalin Kerja Sama dengan 5 Universitas Terkemuka', 'kerja-sama-universitas', 'EduLingo resmi menjalin kerja sama strategis dengan lima universitas terkemuka di Indonesia. Kerja sama ini bertujuan untuk memberikan nilai tambah bagi mahasiswa dalam pengembangan kompetensi bahasa asing.\n\nMelalui kerja sama ini, mahasiswa dari universitas mitra dapat memperoleh konversi SKS untuk kursus bahasa yang diambil di EduLingo. Setiap program yang diselesaikan akan diakui sebagai bagian dari kurikulum perkuliahan.\n\nLima universitas yang telah bergabung adalah Universitas Indonesia, Universitas Gadjah Mada, Institut Teknologi Bandung, Universitas Airlangga, dan Universitas Padjadjaran. EduLingo berencana memperluas kerja sama ke lebih banyak universitas dalam waktu dekat.', 'Kerja sama ini memungkinkan mahasiswa mendapat SKS konversi untuk kursus bahasa yang diambil di EduLingo.', 'Program Baru', 'published', 'a0000000-0000-0000-0000-000000000001', '2026-06-15T00:00:00Z');

-- Seed 3 events
INSERT INTO public.events (title, slug, description, content, event_date, event_time, location, event_type, registration_link, status)
VALUES
  ('Webinar: Kuasai Bahasa Asing untuk Tingkatkan Peluang Karier Global', 'webinar-bahasa-asing-karier', 'Webinar gratis bersama praktisi HRD dan polyglot.', 'EduLingo mengundang kamu untuk mengikuti webinar gratis bertema "Kuasai Bahasa Asing untuk Tingkatkan Peluang Karier Global". Acara ini akan menghadirkan praktisi HRD dari perusahaan multinasional dan seorang polyglot yang menguasai 7 bahasa asing.\n\nWebinar akan membahas:\n• Strategi efektif belajar bahasa asing di tengah kesibukan\n• Bahasa asing yang paling dibutuhkan di dunia kerja saat ini\n• Cara memaksimalkan sertifikat bahasa untuk melamar kerja\n• Sesi tanya jawab dengan para ahli\n\nAcara akan dilaksanakan pada hari Sabtu, 10 Agustus 2026 pukul 10.00 - 12.00 WIB melalui Zoom. Peserta mendapatkan e-sertifikat dan akses rekaman webinar.', '2026-08-10', '10.00 - 12.00 WIB', 'Online (Zoom)', 'Webinar', 'https://forms.google.com/webinar-edulingo', 'published'),
  ('Bootcamp Bahasa Jepang Intensif Level N5', 'bootcamp-bahasa-jepang', 'Program bootcamp intensif 2 hari untuk mempersiapkan ujian JLPT N5.', 'Ikuti Bootcamp Bahasa Jepang Intensif Level N5 yang dirancang khusus untuk pemula yang ingin belajar cepat dan terstruktur.\n\nSelama 2 hari penuh, kamu akan belajar:\n• Hiragana & Katakana dalam 1 hari\n• Kosakata dasar untuk percakapan sehari-hari\n• Pola kalimat sederhana\n• Latihan soal JLPT N5\n\nBootcamp dipandu oleh pengajar native Jepang bersertifikat. Termasuk materi belajar, makan siang, dan sertifikat partisipasi.', '2026-09-01', '08.00 - 16.00 WIB', 'Jakarta Pusat', 'Bootcamp', 'https://forms.google.com/bootcamp-jepang', 'published'),
  ('Kelas Preview Bahasa Inggris Gratis', 'kelas-preview-inggris', 'Rasakan pengalaman belajar bahasa Inggris dengan metode EduLingo secara gratis.', 'Masih ragu untuk memulai? Ikuti Kelas Preview Bahasa Inggris Gratis dan rasakan langsung pengalaman belajar dengan metode EduLingo.\n\nDi kelas preview ini, kamu akan:\n• Mengenal metode belajar interaktif EduLingo\n• Mendapatkan tips belajar bahasa Inggris dari pengajar profesional\n• Konsultasi gratis tentang program yang sesuai\n\nKelas dilaksanakan secara online via Google Meet. Peserta mendapatkan akses trial gratis selama 3 hari setelah kelas.', '2026-08-20', '14.00 - 15.30 WIB', 'Online (Google Meet)', 'Free Class', 'https://forms.google.com/preview-inggris', 'published');
